import { convertMarkdown } from './converter.js';
import { copyResult } from './clipboard.js';

const editor = document.getElementById('editor');
const preview = document.getElementById('preview');
const summary = document.getElementById('conversionSummary');
const tableMode = document.getElementById('tableMode');
const copyRich = document.getElementById('copyRich');
const copyPlain = document.getElementById('copyPlain');
const toast = document.getElementById('toast');
let result;
let toastTimer;

function render() {
  try {
    result = convertMarkdown(editor.value, { tableMode: tableMode.value });
    // Only the closed, escaped HTML vocabulary generated by the converter enters the DOM.
    preview.innerHTML = result.html;
    const { changes } = result;
    const descriptions = [
      changes.headings && `見出し${changes.headings}件を太字に変換`,
      changes.tables && `表${changes.tables}件を${tableMode.value === 'code' ? '等幅表示' : '項目形式'}に変換`,
      changes.tasks && `タスク${changes.tasks}件を☐ / ☑に変換`,
      changes.images && `画像${changes.images}件をリンクに変換`,
      changes.dividers && `区切り線${changes.dividers}件を文字に変換`,
      changes.rawHtml && 'HTMLを文字として表示',
      changes.unsafeLinks && '一部のURLを文字として表示',
      changes.unknown && '非対応の構文を文字として表示',
    ].filter(Boolean);
    const empty = !result.plain.trim();
    summary.textContent = empty ? '見出しや表をSlackで使える書式へ変換します。'
      : descriptions.join(' / ') || 'Slackで使える書式で表示しています。';
    copyRich.disabled = copyPlain.disabled = empty;
    document.getElementById('emptyPreview').hidden = !empty;
  } catch (error) {
    result = null;
    preview.replaceChildren();
    copyRich.disabled = copyPlain.disabled = true;
    summary.textContent = '変換できませんでした。入力内容を確認してください。';
    console.error(error);
  }
}

function showToast(message, error = false) {
  clearTimeout(toastTimer);
  toast.textContent = message;
  toast.classList.toggle('error', error);
  toast.classList.add('show');
  toastTimer = setTimeout(() => toast.classList.remove('show'), 2500);
}

async function copy(rich) {
  if (!result?.plain.trim()) return;
  try {
    await copyResult(result, { rich });
    showToast(rich ? '書式付きでコピーしました' : 'テキストでコピーしました');
  } catch (error) {
    console.error(error);
    showToast('コピーできませんでした。プレビューを選択してコピーしてください。', true);
  }
}

copyRich.addEventListener('click', () => copy(true));
copyPlain.addEventListener('click', () => copy(false));
editor.addEventListener('input', render);
tableMode.addEventListener('change', render);
document.getElementById('clear').addEventListener('click', () => {
  if (editor.value && !confirm('入力内容をクリアしますか？')) return;
  editor.value = '';
  render();
  editor.focus();
});
editor.addEventListener('keydown', (event) => {
  if (event.key !== 'Tab') return;
  event.preventDefault();
  editor.setRangeText('  ', editor.selectionStart, editor.selectionEnd, 'end');
  render();
});

render();
